# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(565, 323)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, -20, 331, 111))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 47, 13))
        self.label_2.setObjectName("label_2")
        self.txtPlain = QtWidgets.QTextEdit(self.centralwidget)
        self.txtPlain.setGeometry(QtCore.QRect(90, 90, 181, 61))
        self.txtPlain.setObjectName("txtPlain")
        self.btnEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnEncrypt.setGeometry(QtCore.QRect(120, 240, 75, 23))
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.btnDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecrypt.setGeometry(QtCore.QRect(200, 240, 75, 23))
        self.btnDecrypt.setObjectName("btnDecrypt")
        self.btnSign = QtWidgets.QPushButton(self.centralwidget)
        self.btnSign.setGeometry(QtCore.QRect(280, 240, 75, 23))
        self.btnSign.setObjectName("btnSign")
        self.btnVerify = QtWidgets.QPushButton(self.centralwidget)
        self.btnVerify.setGeometry(QtCore.QRect(360, 240, 75, 23))
        self.btnVerify.setObjectName("btnVerify")
        self.btnGenKey = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenKey.setGeometry(QtCore.QRect(450, 60, 75, 23))
        self.btnGenKey.setObjectName("btnGenKey")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280, 90, 47, 13))
        self.label_6.setObjectName("label_6")
        self.txtInfor = QtWidgets.QTextEdit(self.centralwidget)
        self.txtInfor.setGeometry(QtCore.QRect(340, 90, 181, 61))
        self.txtInfor.setObjectName("txtInfor")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 160, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(280, 160, 47, 13))
        self.label_8.setObjectName("label_8")
        self.txtSign = QtWidgets.QTextEdit(self.centralwidget)
        self.txtSign.setGeometry(QtCore.QRect(340, 160, 181, 61))
        self.txtSign.setObjectName("txtSign")
        self.txtCipher = QtWidgets.QTextEdit(self.centralwidget)
        self.txtCipher.setGeometry(QtCore.QRect(90, 160, 181, 61))
        self.txtCipher.setObjectName("txtCipher")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 565, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA Cipher"))
        self.label_2.setText(_translate("MainWindow", "PlainText"))
        self.btnEncrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btnDecrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btnSign.setText(_translate("MainWindow", "Sign"))
        self.btnVerify.setText(_translate("MainWindow", "Verify"))
        self.btnGenKey.setText(_translate("MainWindow", "GenKey"))
        self.label_6.setText(_translate("MainWindow", "Infor"))
        self.label_7.setText(_translate("MainWindow", "CipherText"))
        self.label_8.setText(_translate("MainWindow", "Sign"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
